/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PacketRouteImport } from './routes/packet'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProvidersRouteImport } from './routes/dashboard.providers'
import { Route as DashboardGapsRouteImport } from './routes/dashboard.gaps'
import { Route as DashboardFeaturesRouteImport } from './routes/dashboard.features'

const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketRoute = PacketRouteImport.update({
  id: '/packet',
  path: '/packet',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProvidersRoute = DashboardProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGapsRoute = DashboardGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeaturesRoute = DashboardFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclosure': typeof DisclosureRoute
  '/packet': typeof PacketRoute
  '/pricing': typeof PricingRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/dashboard/features': typeof DashboardFeaturesRoute
  '/dashboard/gaps': typeof DashboardGapsRoute
  '/dashboard/providers': typeof DashboardProvidersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/disclosure': typeof DisclosureRoute
  '/packet': typeof PacketRoute
  '/pricing': typeof PricingRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/dashboard/features': typeof DashboardFeaturesRoute
  '/dashboard/gaps': typeof DashboardGapsRoute
  '/dashboard/providers': typeof DashboardProvidersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclosure': typeof DisclosureRoute
  '/packet': typeof PacketRoute
  '/pricing': typeof PricingRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/dashboard/features': typeof DashboardFeaturesRoute
  '/dashboard/gaps': typeof DashboardGapsRoute
  '/dashboard/providers': typeof DashboardProvidersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklist'
    | '/dashboard'
    | '/disclosure'
    | '/packet'
    | '/pricing'
    | '/questionnaire'
    | '/dashboard/features'
    | '/dashboard/gaps'
    | '/dashboard/providers'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklist'
    | '/disclosure'
    | '/packet'
    | '/pricing'
    | '/questionnaire'
    | '/dashboard/features'
    | '/dashboard/gaps'
    | '/dashboard/providers'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/checklist'
    | '/dashboard'
    | '/disclosure'
    | '/packet'
    | '/pricing'
    | '/questionnaire'
    | '/dashboard/features'
    | '/dashboard/gaps'
    | '/dashboard/providers'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistRoute: typeof ChecklistRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DisclosureRoute: typeof DisclosureRoute
  PacketRoute: typeof PacketRoute
  PricingRoute: typeof PricingRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packet': {
      id: '/packet'
      path: '/packet'
      fullPath: '/packet'
      preLoaderRoute: typeof PacketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/providers': {
      id: '/dashboard/providers'
      path: '/providers'
      fullPath: '/dashboard/providers'
      preLoaderRoute: typeof DashboardProvidersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gaps': {
      id: '/dashboard/gaps'
      path: '/gaps'
      fullPath: '/dashboard/gaps'
      preLoaderRoute: typeof DashboardGapsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/features': {
      id: '/dashboard/features'
      path: '/features'
      fullPath: '/dashboard/features'
      preLoaderRoute: typeof DashboardFeaturesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardFeaturesRoute: typeof DashboardFeaturesRoute
  DashboardGapsRoute: typeof DashboardGapsRoute
  DashboardProvidersRoute: typeof DashboardProvidersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFeaturesRoute: DashboardFeaturesRoute,
  DashboardGapsRoute: DashboardGapsRoute,
  DashboardProvidersRoute: DashboardProvidersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistRoute: ChecklistRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DisclosureRoute: DisclosureRoute,
  PacketRoute: PacketRoute,
  PricingRoute: PricingRoute,
  QuestionnaireRoute: QuestionnaireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
